require './server'
require './controllers/login_controller'
require './controllers/register_controller'
require './controllers/main_menu_controller'
require './controllers/my_profile_controller'
require './controllers/change_user_data_controller'
require './controllers/transfer_controller'
require './controllers/transfer_failed_controller'
require './controllers/transfer_success_controller'
require './controllers/change_account_data_controller'
require './controllers/market_controller'

use LoginController
use RegisterController
use MainMenuController
use MyProfileController
use TransferController
use TransferSuccessController
use TransferFailedController
use ChangeUserDataController
use ChangeAccountDataController
use MarketController
run App
