
#version ruby

ruby '3.2.2'

source "https://rubygems.org"

# gemas usadas

gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib'
gem 'rackup'
gem 'puma', '~> 6.6'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'bcrypt', '~> 3.1.7'
group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-rails'
end
